RACK_DIR ?= ../Rack-SDK

SOURCES = src/plugin.cpp src/ra-vca.cpp src/ra-gnawbz-4x.cpp src/ra-gnawbz-1x4.cpp src/ra-ulfo.cpp src/ra-scaler.cpp src/ra-endless.cpp src/ra-yscope.cpp src/ra-shapes.cpp src/ra-chance.cpp
DISTRIBUTABLES += $(wildcard res/*)

include $(RACK_DIR)/plugin.mk
