#include "rack.hpp"

using namespace rack;

Plugin *pluginInstance;
extern Model *modelRaVca;
extern Model *modelRaGnawbz;
extern Model *modelRaMacro;
extern Model *modelRaUlfo;
extern Model *modelRaRanger;
extern Model *modelRaReflectingPool;
extern Model *modelRaGlitch;
extern Model *modelRaShapes;
extern Model *modelRaTyche;
extern Model *modelRaVipberus;
extern Model *modelRaSeerMini;
extern Model *modelRaBlank;
extern Model *modelRaAdsr;
extern Model *modelRaKlock;
extern Model *modelRaButtons;
extern Model *modelRaM2;
extern Model *modelRaMagus;
extern Model *modelRaNtet;
extern Model *modelRaThink;
extern Model *modelRaAccumulator;
extern Model *modelRaZeno;
extern Model *modelRaSeer;
extern Model *modelRaChord;
extern Model *modelRaTracker;
extern Model *modelRaJust;
extern Model *modelRaQuant;
extern Model *modelRaMothership;
extern Model *modelRaKick;
extern Model *modelRaSnare;
extern Model *modelRaTom;
extern Model *modelRaClap;
extern Model *modelRaHat;
extern Model *modelRaCymbal;
extern Model *modelRaRide;
extern Model *modelRaMeteor;
extern Model *modelRaTuner;
extern Model *modelRaVash;
extern Model *modelRaVnote;
extern Model *modelRaKarplusStrong;
extern Model *modelRaFreeberd;
extern Model *modelRaDelayCv;
extern Model *modelRaKrush;

void init(Plugin *p) {
    pluginInstance = p;
    p->addModel(modelRaVca);
    p->addModel(modelRaGnawbz);
    p->addModel(modelRaMacro);
    p->addModel(modelRaUlfo);
    p->addModel(modelRaRanger);
    p->addModel(modelRaReflectingPool);
    p->addModel(modelRaGlitch);
    p->addModel(modelRaShapes);
    p->addModel(modelRaTyche);
    p->addModel(modelRaVipberus);
    p->addModel(modelRaSeerMini);
    p->addModel(modelRaBlank);
    p->addModel(modelRaAdsr);
    p->addModel(modelRaKlock);
    p->addModel(modelRaButtons);
    p->addModel(modelRaM2);
    p->addModel(modelRaMagus);
	p->addModel(modelRaNtet);
	p->addModel(modelRaThink);
	p->addModel(modelRaAccumulator);
	p->addModel(modelRaZeno);
	p->addModel(modelRaSeer);
	p->addModel(modelRaChord);
	p->addModel(modelRaTracker);
	p->addModel(modelRaJust);
	p->addModel(modelRaQuant);
	p->addModel(modelRaMothership);
	p->addModel(modelRaKick);
	p->addModel(modelRaSnare);
	p->addModel(modelRaTom);
	p->addModel(modelRaClap);
	p->addModel(modelRaHat);
	p->addModel(modelRaCymbal);
	p->addModel(modelRaRide);
	p->addModel(modelRaMeteor);
	p->addModel(modelRaTuner);
	p->addModel(modelRaVash);
	p->addModel(modelRaVnote);
	p->addModel(modelRaKarplusStrong);
	p->addModel(modelRaFreeberd);
	p->addModel(modelRaDelayCv);
	p->addModel(modelRaKrush);
}
